#!/bin/bash

# 运行 clippy
cargo clippy  --manifest-path ./Cargo.toml --fix

# 如果 clippy 失败，阻止 push
if [ $? -ne 0 ]; then
   echo "Clippy found issues in sub_crate. Please fix them before pushing."
   exit 1
fi

cargo test

# 允许 push
exit 0